In [1]:
!pip list

Package                      Version
---------------------------- -----------
absl-py                      2.3.1
asttokens                    3.0.0
astunparse                   1.6.3
attrs                        25.3.0
cachetools                   5.5.2
certifi                      2025.8.3
charset-normalizer           3.4.2
colorama                     0.4.6
comm                         0.2.3
debugpy                      1.8.15
decorator                    5.2.1
dm-tree                      0.1.9
docstring_parser             0.17.0
einops                       0.8.1
etils                        1.13.0
exceptiongroup               1.3.0
executing                    2.2.0
flatbuffers                  25.2.10
fsspec                       2025.7.0
gast                         0.6.0
google-auth                  2.40.3
google-auth-oauthlib         1.2.2
google-pasta                 0.2.0
grpcio                       1.74.0
h5py                         3.14.0
idna                         3.1


[notice] A new release of pip available: 22.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
!pip install "tensorflow<2.16" tensorflow_hub tensorflow_datasets


[notice] A new release of pip available: 22.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
pip install numpy<2 pandas matplotlib scikit-learn tensorflow tensorflow_hub tensorflow_datasets

Note: you may need to restart the kernel to use updated packages.


The system cannot find the file specified.


In [15]:
!pip install numpy
!pip install tensorflow
!pip install tensorflow_hub
!pip install tensorflow_datasets

import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
# tensorflow packages
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_datasets as tfds

print(tf.__version__)


[notice] A new release of pip available: 22.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip available: 22.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip available: 22.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip



2.15.1



[notice] A new release of pip available: 22.3.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
train_data, validation_data, test_data = tfds.load(name="imdb_reviews",
                                                 split=("train[:60%]", 'train[60%:]', 'test'),
                                                 as_supervised=True)

In [6]:
train_data

<_PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>

In [16]:
hub_layer = hub.KerasLayer("https://kaggle.com/models/google/gnews-swivel/frameworks/TensorFlow2/variations/tf2-preview-20dim/versions/1", output_shape=[20],
                           input_shape=[], dtype=tf.string)

model =tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1, activation='sigmoid'))

model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer_1 (KerasLayer)  (None, 20)                400020    
                                                                 
 dense_2 (Dense)             (None, 16)                336       
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 400373 (1.53 MB)
Trainable params: 353 (1.38 KB)
Non-trainable params: 400020 (1.53 MB)
_________________________________________________________________


In [22]:
model.compile(optimizer='Adam', loss= tf.losses.BinaryCrossentropy(from_logits=True), metrics=['accuracy'])

In [23]:
model.fit(train_data.shuffle(1000).batch(1000), epochs=10, validation_data=validation_data.batch(100),verbose=1)

Epoch 1/10
15/15 [==============================] - 6s 275ms/step - loss: 0.6028 - accuracy: 0.6722 - val_loss: 0.6010 - val_accuracy: 0.6774
Epoch 2/10
15/15 [==============================] - 4s 238ms/step - loss: 0.5964 - accuracy: 0.6795 - val_loss: 0.5953 - val_accuracy: 0.6848
Epoch 3/10
15/15 [==============================] - 4s 240ms/step - loss: 0.5917 - accuracy: 0.6839 - val_loss: 0.5905 - val_accuracy: 0.6877
Epoch 4/10
15/15 [==============================] - 4s 250ms/step - loss: 0.5876 - accuracy: 0.6877 - val_loss: 0.5866 - val_accuracy: 0.6904
Epoch 5/10
15/15 [==============================] - 4s 265ms/step - loss: 0.5839 - accuracy: 0.6912 - val_loss: 0.5833 - val_accuracy: 0.6936
Epoch 6/10
15/15 [==============================] - 4s 239ms/step - loss: 0.5806 - accuracy: 0.6943 - val_loss: 0.5804 - val_accuracy: 0.6950
Epoch 7/10
15/15 [==============================] - 4s 238ms/step - loss: 0.5777 - accuracy: 0.6963 - val_loss: 0.5780 - val_accuracy: 0.6970
Epoch 

In [24]:
model.fit(train_data.shuffle(1000).batch(1000), epochs=10, validation_data=validation_data.batch(100),verbose=1)

Epoch 1/10
15/15 [==============================] - 3s 234ms/step - loss: 0.5684 - accuracy: 0.7053 - val_loss: 0.5697 - val_accuracy: 0.7062
Epoch 2/10
15/15 [==============================] - 3s 234ms/step - loss: 0.5667 - accuracy: 0.7070 - val_loss: 0.5683 - val_accuracy: 0.7083
Epoch 3/10
15/15 [==============================] - 4s 241ms/step - loss: 0.5653 - accuracy: 0.7091 - val_loss: 0.5669 - val_accuracy: 0.7087
Epoch 4/10
15/15 [==============================] - 3s 236ms/step - loss: 0.5637 - accuracy: 0.7105 - val_loss: 0.5657 - val_accuracy: 0.7107
Epoch 5/10
15/15 [==============================] - 3s 232ms/step - loss: 0.5625 - accuracy: 0.7113 - val_loss: 0.5645 - val_accuracy: 0.7125
Epoch 6/10
15/15 [==============================] - 3s 232ms/step - loss: 0.5615 - accuracy: 0.7124 - val_loss: 0.5635 - val_accuracy: 0.7138
Epoch 7/10
15/15 [==============================] - 4s 237ms/step - loss: 0.5599 - accuracy: 0.7127 - val_loss: 0.5624 - val_accuracy: 0.7152
Epoch 

In [25]:
model.evaluate(test_data.batch(100))

250/250 [==============================] - 5s 19ms/step - loss: 0.5627 - accuracy: 0.7125


[0.5626729130744934, 0.7124800086021423]

In [26]:
train_example_batch, train_labels_batch = next(iter(train_data.batch(10)))

In [27]:
train_example_batch

<tf.Tensor: shape=(10,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell 

In [28]:
train_labels_batch

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([0, 0, 0, 1, 1, 1, 0, 0, 0, 0], dtype=int64)>

In [34]:
embedding = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub. KerasLayer(embedding,input_shape=[], dtype=tf.string, trainable=True)

In [35]:
hub_layer(train_example_batch[:3])

<tf.Tensor: shape=(3, 20), dtype=float32, numpy=
array([[ 1.765786  , -3.882232  ,  3.9134233 , -1.5557289 , -3.3362343 ,
        -1.7357955 , -1.9954445 ,  1.2989551 ,  5.081598  , -1.1041286 ,
        -2.0503852 , -0.72675157, -0.65675956,  0.24436149, -3.7208383 ,
         2.0954835 ,  2.2969332 , -2.0689783 , -2.9489717 , -1.1315987 ],
       [ 1.8804485 , -2.5852382 ,  3.4066997 ,  1.0982676 , -4.056685  ,
        -4.891284  , -2.785554  ,  1.3874227 ,  3.8476458 , -0.9256538 ,
        -1.896706  ,  1.2113281 ,  0.11474707,  0.76209456, -4.8791065 ,
         2.906149  ,  4.7087674 , -2.3652055 , -3.5015898 , -1.6390051 ],
       [ 0.71152234, -0.6353217 ,  1.7385626 , -1.1168286 , -0.5451594 ,
        -1.1808156 ,  0.09504455,  1.4653089 ,  0.66059524,  0.79308075,
        -2.2268345 ,  0.07446612, -1.4075904 , -0.70645386, -1.907037  ,
         1.4419787 ,  1.9551861 , -0.42660055, -2.8022065 ,  0.43727064]],
      dtype=float32)>

In [39]:
model=tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation="relu"))
model.add(tf.keras.layers.Dense(1))

In [40]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer_2 (KerasLayer)  (None, 20)                400020    
                                                                 
 dense_4 (Dense)             (None, 16)                336       
                                                                 
 dense_5 (Dense)             (None, 1)                 17        
                                                                 
Total params: 400373 (1.53 MB)
Trainable params: 400373 (1.53 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [47]:
model.compile(optimizer='adam', loss=tf.keras.losses.BinaryCrossentropy(from_logits=True), metrics=['accuracy'])

In [53]:
history = model.fit(train_data.shuffle(10000).batch(100), epochs=25,
                    validation_data = validation_data.batch(100), verbose=1)

Epoch 1/25
150/150 [==============================] - 9s 47ms/step - loss: 0.8279 - accuracy: 0.6016 - val_loss: 0.6113 - val_accuracy: 0.6469
Epoch 2/25
150/150 [==============================] - 6s 38ms/step - loss: 0.5532 - accuracy: 0.6970 - val_loss: 0.5113 - val_accuracy: 0.7372
Epoch 3/25
150/150 [==============================] - 5s 34ms/step - loss: 0.4592 - accuracy: 0.7729 - val_loss: 0.4384 - val_accuracy: 0.7907
Epoch 4/25
150/150 [==============================] - 6s 36ms/step - loss: 0.3847 - accuracy: 0.8240 - val_loss: 0.3911 - val_accuracy: 0.8271
Epoch 5/25
150/150 [==============================] - 5s 35ms/step - loss: 0.3270 - accuracy: 0.8526 - val_loss: 0.3572 - val_accuracy: 0.8440
Epoch 6/25
150/150 [==============================] - 6s 37ms/step - loss: 0.2831 - accuracy: 0.8786 - val_loss: 0.3344 - val_accuracy: 0.8507
Epoch 7/25
150/150 [==============================] - 6s 39ms/step - loss: 0.2474 - accuracy: 0.8970 - val_loss: 0.3253 - val_accuracy: 0.8507

In [55]:
results = model.evaluate(test_data.batch(100), verbose=2)
for name, value in zip(model.metrics_names, results): 
       print("%s: %.3f" % (name, value))

250/250 - 4s - loss: 0.6562 - accuracy: 0.8426 - 4s/epoch - 15ms/step
loss: 0.656
accuracy: 0.843
